server:
  port: 8999
spring: 
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shin-minkyung/baseAuthConfig
          force-pull: true
          search-paths:
          - serviceA
          - HecateAuth
    bus:
      trace:
        enabled: true
eureka:
  client:
    enabled: true
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/         